chrome_archive_service:
  source: git@github.com:tmathmeyer/chrome_archive_service.git

dotfiles:
  source: git@github.com:tmathmeyer/dotfiles

eu4_hacks:
  source: git@github.com:tmathmeyer/eu4_hacks.git

googletest:
  source: git@github.com:tmathmeyer/googletest.git

nginx:
  source: git@github.com:tmathmeyer/nginx_config_parser.git

paste_service:
  source: git@github.com:tmathmeyer/JankyPaste.git

hatsuden:
  source: git@github.com:tmathmeyer/hatsuden.git

remarkable:
  source: git@github.com:tmathmeyer/remarkable.git

impulse:
  source: git@github.com:tmathmeyer/impulse.git

rules:
  source: symlink://impulse/rules
  requires: impulse

scrapers:
  source: git@github.com:tmathmeyer/scrapers.git

scrapers/cs:
  source: git@github.com:tmathmeyer/scrapers.cs.git
  requires: scrapers

scrapers/jdb:
  source: git@github.com:tmathmeyer/scrapers.jdb.git
  requires: scrapers

scrapers/msdocs:
  source: git@github.com:tmathmeyer/scrapers.msdocs.git
  requires: scrapers

scrapers/upc:
  source: git@github.com:tmathmeyer/upc_scraping.git
  requires: scrapers

xpp:
  source: git@github.com:tmathmeyer/xpp.git

api_core:
  source: git@github.com:tmathmeyer/api_core.git

nginx_docker_bridge:
  source: git@github.com:tmathmeyer/nginx_docker_bridge.git
  requires: nginx,api_core