langs("C")

cpp_header (
  name = "tuple",
  srcs = [ "tuple.h", ],
)

cpp_header (
  name = "location",
  srcs = [ "location.h" ],
)

cpp_header (
  name = "check",
  srcs = [ "check.h" ],
)

cpp_header (
  name = "proxy_ptr",
  srcs = [ "proxy_ptr.h" ],
)